# File: _config.yml
# Configuration for Jekyll website

title: AugFJTan Programming Blog
# email: # your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on programming, computer science, robotics and other related topics.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: # jekyllrb
github_username:  AugFJTan

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-github-comments
exclude:
  - Gemfile
  - Gemfile.lock
github_comments:
  repo: "AugFJTan/AugFJTan.github.io"
  comment_template: comment.html
  comments_template: comments.html
